config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  get 'blog', to: "posts#index"
  get 'blog/:id', to: "posts#show"
  put 'account/post/:id', to: "accounts/posts#update_picture", as: "update_picture"
  post '/', to: "subscribers#create", as: "create_subscriber"
  post 'contact', to: "contacts#create", as: "create_contact"


  resources :locations, only: [:index]

  resource :account, only: [:show, :edit, :update] do
    resources :posts, only: [:show, :create, :update, :destroy], module: :accounts
    resources :locations, only: [:create, :destroy], module: :accounts
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :username, presence: true
  validates :email, presence: true
  validates :description, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "200x200>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  validates :name, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :picture,
    styles: { medium: "400x400>", thumb: "100x100>" }
  belongs_to :user
  has_many :post_pictures, dependent: :destroy

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :post_pictures, reject_if: lambda { |p| p['post_picture'].nil? }, allow_destroy: true
end

app/models/post_picture.rb
class PostPicture < ActiveRecord::Base
  belongs_to :post

  has_attached_file :picture,
    styles: { medium: "400x400>", thumb: "100x100>" }
  validates_attachment_presence :picture
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/accounts/locations_controller.rb
class Accounts::LocationsController < ApplicationController
  # before_action :authenticate_use@r!
  # after_action :verify_authorized
  # after_action :verify_policy_scoped

  def create
    @location = Location.new(location_params)
    # authorize @post
    if @location.save
      redirect_to account_path
    else
     render :new
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to account_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :description, :link)
  end
end

app/controllers/accounts/posts_controller.rb
class Accounts::PostsController < ApplicationController
  # before_action :authenticate_user!
  before_action :find_post, only: [:show, :update, :update_picture, :destroy]
  # after_action :verify_authorized
  # after_action :verify_policy_scoped
  respond_to :html, :json

  def show
  end

  def create
    @post = Post.new(post_params)
    # authorize @post
    if @post.save
      # flash[:notice] = "Votre article a bien été sauvegardé."
      redirect_to account_path
    else
      # flash[:notice] = "Une erreur est survenue. Votre article n'a pas été sauvegardé."
      redirect_to account_path
    end
  end

  def update
    @post.update(post_params)
    respond_with @post
  end

  def update_picture
    @post.update(post_picture_param)
    redirect_to account_post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to account_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :subtitle, :description, :picture, :author, post_pictures_attributes: [:id, :picture, :_destroy])
  end

  def post_picture_param
    params.require(:post).permit(:picture)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @location = Location.new
    @locations = Location.all
    @post = Post.new
    @posts = Post.all
  end

  # def edit
  # end

  # def update
  #   current_user.update(account_params)
  #   redirect_to account_path
  # end

  private

  def account_params
    params.require(:user).permit(:name, :email, :picture)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception


  # before_action :authenticate_user!, unless: :pages_controller_or_posts_controller?
  # faire un only plutôt qu'un unless, et faire un only sur le post controller du account controller

  # after_action :verify_authorized, except:  :index, unless: :devise_or_pages_controller_or_posts_controller_or_admin?
  # after_action :verify_policy_scoped, only: :index, unless: :devise_or_pages_controller_or_posts_controller_or_admin?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def devise_or_pages_controller_or_posts_controller_or_admin?
    devise_controller? || pages_controller_or_posts_controller? || params[:controller] =~ /^admin/
  end

  def pages_controller_or_posts_controller_or?
    controller_name == "pages" || controller_name == "posts"  # Brought by the `high_voltage` gem
  end

  def user_not_authorized
    flash[:error] = I18n.t('controllers.application.user_not_authorized', default: "You can't access this page.")
    redirect_to(root_path)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)
    # authorize @post
    if @contact.save
      flash[:alert] = "Nous reviendrons vers vous très bientôt!"
      redirect_to page_path('contact')
    else
      flash[:alert] = "Une erreur est survenue, merci de réessayer plus tard."
      redirect_to page_path('contact')
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:username, :email, :description)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.title location.name
      marker.infowindow ( "<div class='map-infowindow'>" + "<div class='map-infowindow-header'>" + "<strong>" + '<a href="http://' + location.link + '" target="_blank" >' + location.name.upcase + "</a>" + "</strong>" + "<br>" + "</div>" + "<em>" + location.address + "</em>" + "<div class='map-infowindow-body'>" + location.description + "</div>" + "</div>")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def create
    @subscriber = Subscriber.new(subscriber_param)
    # authorize @post
    if @subscriber.save
      flash[:alert] = "Merci d'avoir souscrit à notre newsletter!"
      redirect_to root_path
    else
      flash[:alert] = "Une erreur est survenue. Veuillez vérifier votre email!"
      redirect_to root_path
    end
  end

  private

  def subscriber_param
    params.require(:subscriber).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/accounts/posts/_post_pictures_fields.html.erb
<div class="nested-fields">
  <%= f.file_field :picture %>
  <%= link_to_remove_association "Supprimer", f %>
</div>

app/views/accounts/posts/new.html.erb
<div class="container">
  <div class="text-center">
    <h2>Create a new post</h2>
  </div>
  <div class="col-sm-6 col-sm-offset-3">
    <div class="box-form">
    <%= simple_form_for(@post, html: {multipart: true}, url: account_posts_path) do |f| %>
      <%# @post.errors.full_messages %>
      <%= f.error_notification %>

      <%#= f.association :tag?, as: :select, label_method: :name, label: false, placeholder: "Type the name of the tag" %> <!-- PEUT SERVIR POUR LES TAGS -->
      <%= f.input :title %>
      <%= f.input :subtitle %>
      <%= f.input :description %>
      <%= f.input :picture %> <!-- TODO Add a drag and drop ??? -->
      <%= f.input :author %>
      <%= f.button :submit, class: "submit-btn" %>
    <% end %>
    </div>
  </div>
</div>

app/views/accounts/posts/show.html.erb
<div class="container">
  <div class="padded">
    <div class="box-form">
      <%= link_to account_path do %>
        <i class="fa fa-chevron-left back"></i>
      <% end %>
      <div class="trash-show">
        <%= link_to account_post_path(@post), method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="fa fa-times"></i>
        <% end %>
      </div>
      <div class="title-padding">
        <h2>
          <%= best_in_place @post, :title, url: account_post_path(@post), class: "edit-title" %>
        </h2>
      </div>
      <p>
        <b>Sous-titre :</b>
        <%= best_in_place @post, :subtitle, url: account_post_path(@post), class: "edit-subtitle" %>
      </p>
      <p>
        <b>Description:</b>
<!--         TO DO: better updating method, pb with the refresh
 -->        <%= best_in_place @post, :description, url: account_post_path(@post), class: "edit-description", :as => :textarea, display_with: :simple_format %>
      </p>
      <p>
        <b>Auteur:</b>
        <%= best_in_place @post, :author, url: account_post_path(@post), class: "edit-author" %>
      </p>

      <%= image_tag @post.picture.url(:medium) %>
      <%= simple_form_for(@post, html: {multipart: true}, url: update_picture_path(@post), method: :put) do |f| %>
        <%= f.input :picture, label: "Photo" %>
        <%= f.submit "Editer la photo",  class: "btn submit-btn" %>
      <% end %>
<!-- TO DO :
INCORPORER LELEMENT PR EDITER PLUSIEURS PHOTOS
      <%#= f.fields_for :post_pictures do |picture| %>
        <%#= render 'posts/post_pictures_fields', f: picture %>
      <%# end %>
      <div class="links">
        <%#= link_to_add_association 'Ajouter une photo', f, :post_pictures, partial: 'accounts/posts/post_pictures_fields' %>
      </div> -->
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<!-- RIGHT CONTENT BEGINS -->
<div class="form-wrapper inactive" id="layer1">
  <div class="post-form">
    <%= render 'posts/form' %>
  </div>
</div>

<div class="form-wrapper active" id="layer2">
  <% @posts.each do |post| %>
    <div class="mini-card">
      <div class="inside-card">
        <%= link_to account_post_path(post) do %>
          <h3><%= post.title %></h3>
          <p><%= post.subtitle %></p>
          <% if post.picture? %>
            <%= image_tag post.picture.url(:thumb), class: "avatar"%>
          <% end %>
        <% end %>
        <div class="trash text-center">
          <%= link_to account_post_path(post), method: :delete, data: {confirm: "Êtes-vous sûr de vouloir supprimer cet article?"} do %>
            <i class="fa fa-times"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
    <div class="new-card">
    <a href=""><div class="new-inside-card">
      <i class="plus-icon"></i>
    </div></a>
  </div>
</div>

<div class="form-wrapper inactive" id="layer3">
  <div class="post-form">
    <%= render 'locations/form' %>
  </div>
</div>

<div class="form-wrapper inactive" id="layer4">
  <h2 style="text-align: center">Vos lieux</h2>
  <% @locations.each do |location| %>
    <div style="position: relative; width: 90%; margin-left: auto; margin-right: auto; width: 30%; margin-bottom: 10px; border-style: solid; border-size: 2.5px; border-radius: 2.5px; border-color: #2A316D; font-size: 18px">
      <p style="color: #2A316D; position: relative; margin-top: 10px; margin-bottom: 10px; margin-left: 10px">
        <%= location.name %> - <%= link_to account_location_path(location), method: :delete do %>
          <i class="fa fa-times"></i>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

<!-- RIGHT CONTENT ENDS -->

<!-- LEFT CONTENT BEGINS -->
<div class="content-left">
  <h2>Bonjour <%= current_user.name %></h2>
  <br>
  <ul>
    <li><a href="#1" id="handler2">Voir mes publications</a></li>
    <li><a href="#2" id="handler1">Créer une nouvelle publication</a></li>
    <li><a href="#3" id="handler4">Voir les lieux</a></li>
    <li><a href="#4" id="handler3">Créer un lieu</a></li>
  </ul>
</div>
<!-- LEFT CONTENT ENDS -->

app/views/contacts/_form.html.erb
<%= simple_form_for(Contact.new, url: create_contact_path) do |f| %>
  <%= f.error_notification %>
  <%= f.input :username, label: "Nom" %>
  <%= f.input :email %>
  <%= f.input :description, label: "Votre demande" %>
  <%= f.button :submit, "Envoyer", class: "submit-btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "Diametre" %></title>
  <meta name="description" content="<%= (yield(:description) || "").squish %>">


  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <%= render "shared/navbar" %>
  <%= yield %>


  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyD48TV49s1qIAqlgT_F4kDCAZWWO3wQvSA" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag :application %>
  <%= yield(:after_js) %>

</body>
</html>

app/views/locations/_form.html.erb
<h2 style="text-align: center">Ajouter un lieu</h2>
<div class="box-form" id="big-form">
  <%= form_for @location, url: account_locations_path, method: :post do |f| %>
    <div class="location_name">
      <%= f.label "Nom du lieu" %>
      <%= f.text_field :name %>
    </div>
    <div class="location_adresse">
      <%= f.label "Adresse" %>
      <%= f.text_field :address, id: 'user_input_autocomplete_address' %>
    </div>
    <div class="location_description">
      <%= f.label "Description" %>
      <%= f.text_area :description, class: "text optional form-control", as: :text %>
    </div>
    <input id="street_number" name="street_number" type="hidden" disabled>
    <input id="route" name="route" type="hidden" disabled>
    <input id="locality" name="locality" type="hidden"disabled>
    <input id="country" name="country" type="hidden" disabled>
    <div class="">
      <%= f.label "Lien" %>
      <%= f.text_field :link %>
    </div>
   <%= f.submit "Créer", class:"btn" %>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      google.maps.event.addDomListener(window, 'load', function() {
        initializeAutocomplete('user_input_autocomplete_address');
      });
    });
  <% end %>
<% end %>

app/views/locations/index.html.erb
<!-- MAP BEGINS -->

  <div class="map-wrapper">
    <div id="map"></div>
  </div>
<!-- MAP ENDS -->

<!-- LEFT CONTENT BEGINS -->
<div class="content-left active">
    <h2 style="text-align: center">La carte "jeune création"</h2>
    <p>Quelques propositions d’expositions de jeunes artistes en région parisienne:</p>
    <ul class="locations-list">
      <div id="sidebar_container">
      </div>
    </ul>
    <p>
      <em>
        N’hésitez pas à nous envoyer vos suggestions à l’adresse suivante:
info@diametre.org
      </em>
    </p>
</div>
<!-- LEFT CONTENT ENDS -->

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
    var mapStyle = [
      {
          "featureType": "administrative",
          "elementType": "all",
          "stylers": [
              {
                  "visibility": "on"
              },
              {
                  "lightness": 33
              }
          ]
      },
      {
          "featureType": "landscape",
          "elementType": "all",
          "stylers": [
              {
                  "color": "#f2e5d4"
              }
          ]
      },
      {
          "featureType": "poi.park",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#c5dac6"
              }
          ]
      },
      {
          "featureType": "poi.park",
          "elementType": "labels",
          "stylers": [
              {
                  "visibility": "on"
              },
              {
                  "lightness": 20
              }
          ]
      },
      {
          "featureType": "road",
          "elementType": "all",
          "stylers": [
              {
                  "lightness": 20
              }
          ]
      },
      {
          "featureType": "road.highway",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#c5c6c6"
              }
          ]
      },
      {
          "featureType": "road.arterial",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#e4d7c6"
              }
          ]
      },
      {
          "featureType": "road.local",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#fbfaf7"
              }
          ]
      },
      {
          "featureType": "water",
          "elementType": "all",
          "stylers": [
              {
                  "visibility": "on"
              },
              {
                  "color": "#acbcc9"
              }
          ]
      }
    ];

      function createSidebarLi(json){
        return ("<li><a>" + json.marker_title + "</a></li>");
      };

      function bindLiToMarker($li, marker){
        $li.on('click', function(){
          handler.getMap().setZoom(14);
          marker.setMap(handler.getMap());
          marker.panTo();
          google.maps.event.trigger(marker.getServiceObject(), 'click');
        })
      };

      function createSidebar(json_array){
        _.each(json_array, function(json){
          var $li = $( createSidebarLi(json) );
          $li.appendTo('#sidebar_container');
          bindLiToMarker($li, json.marker);
        });
      };

      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: {id: 'map'}, provider: { styles: mapStyle }}, function(){
        var json_array = <%= raw @markers.to_json %>;
        var markers = handler.addMarkers(json_array);
        _.each(json_array, function(json, index){
          json.marker = markers[index];
        });

        createSidebar(json_array);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/pages/contact.html.erb
<div class="form-wrapper">
  <div class="post-form">
     <h2 style="text-align: center">nous contacter</h2>
     <div class="box-form" id="big-form">
         <%= render 'contacts/form' %>
     </div>
  </div>
</div>
<div class="content-left">
  <h2>Informations</h2>
  <ul class="unstyled" style="padding:22px;">
    <li>Vous pouvez nous contacter à l'adresse
    <span>
      <%= mail_to "diametre.development@gmail.com" do %>
        contact@diametre.com
      <% end %>
    </span> ou via le formulaire sur cette même page.
    </li>
    <li>Vous pouvez trouver des informations sur l'association et ses membres <a href="/about">ICI</a></li>
  </ul>
</div>

<!--<div class="padded">
  <div class="container">
    <div class="row">
      <%= render "shared/flashes" %>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="yellow-form">
          <h2>Nous contacter</h2>
          <div class="text-left">

          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="yellow-form">
          <h2></h2>
          <ul class='list-unstyle contact-list'>
            <li>
              <%= mail_to "diametre.development@gmail.com" do %>
                contact@diametre.com
              <% end %>
            </li>
            <li>Téléphone</li>
            <li>Adresse</li>
            <li>Status?</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>-->

app/views/pages/home.html.erb
<%= content_for(:title) do %>
  Home
<% end %>

<%= content_for(:description) do %>
  <%# TODO %>
<% end %>

<div class="gcontainer">
  <%= render "shared/flashes" %>
  <div class="grow">
    <div class="gvignette" id="divbig">
      <h2>MUSEE IMAGINAIRE</h2>
      <!--<p>Exposition virtuelle mensuelle mise en œuvre par {{gars en question}}</p>-->
    </div>
    <div class="gvignette" id="divsmall">
      <h2>DIA-DATE</h2>
     <!-- <p>Rencontre entre jeunes artistes et professionnels du monde de l’art au 104.</p>-->
    </div>
    <div class="gvignette" id="divsmall">
      <h2>CALENDRIER</h2>
      <!--<p>Inscrivez-vous aux événements</p>-->
    </div>
  </div>
  <div class="grow">
    <div class="gvignette" id="divsmall">
      <%= link_to locations_path do %>
        <h2>LA CARTE</h2>
      <% end %>
<!--       <p></p> -->
    </div>
    <div class="gvignette" id="divbig">
      <h2>MINI EXPOSITION</h2>
      <!--<p>Un membre de l'association expose le travail d’un artiste qu’il aime particulièrement.</p>-->
    </div>
    <div class="gvignette" id="divsmall">
      <h2>SOUTENIR L'ASSOCIATION</h2>
      <!--<p>Donnez-nous de l'argent et des tableaux</p>-->
    </div>
  </div>
  <div class="grow">
    <div class="gvignette" id="divsmall">
      <%= link_to page_path('about') do %>
        <h2>Une association pour la jeune création</h2>
      <% end %>
      <!--<p>Nos recommandation culture à Paname</p>-->
    </div>
    <div class="gvignette" id="divsmall">
      <div class="subscribe-trigger">
        <h2>NEWSLETTER - Cliquer pour s'abonner</h2>
      </div>
      <div class="subscribe-form hidden">
        <%= simple_form_for(Subscriber.new(), url: create_subscriber_path) do |f| %>
          <%= f.error_notification %>
          <%= f.input :email, label: false, placeholder: 'Email' %>
          <%= f.button :submit, "S'abonner", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
    <div class="gvignette" id="divbig">
      <%= link_to blog_path do %>
        <h2>BLOG</h2>
      <% end %>
      <!--<p>Le blog de l'association ;)</p>-->
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<h2 style="text-align: center">Créer un nouvel article</h2>
<div class="box-form" id="big-form">
    <%= simple_form_for(@post, html: {multipart: true}, url: account_posts_path) do |f| %>
      <%# @post.errors.full_messages %>
      <%= f.error_notification %>

      <%#= f.association :tag?, as: :select, label_method: :name, label: false, placeholder: "Type the name of the tag" %> <!-- PEUT SERVIR POUR LES TAGS -->
      <%= f.input :title, label: 'Titre' %>
      <%= f.input :subtitle, label: 'Sous-titre' %>
      <%= f.input :description, as: :text %>
<!--       PREVIOUS FORM TO UPLOAD PICTURES -->
      <%#= f.input :picture %> <!-- TODO Add a drag and drop ??? -->
      <%#= f.simple_fields_for :post_pictures do |p| %>
        <%#= p.input :picture %>
        <%#= p.input :_destroy, as: :boolean, label: 'Supprimer la photo' %>
      <%# end %>
      <!-- c'est tjrs celle qu'on peut voir sur le site -->
      <%= f.simple_fields_for :post_pictures do |picture| %>
        <%= render 'posts/post_pictures_fields', f: picture %>
      <% end %>
<!--       if we want to see the pictures while uploading: go this link and follow tutorial
      la docu de la gem: https://github.com/nathanvda/cocoon
      http://www.liooo.engineer/blog/2014/11/22/building-multiple-file-upload-form-in-rails-way/ -->
      <div class="links">
        <%= link_to_add_association 'Ajouter une photo', f, :post_pictures, partial: 'accounts/posts/post_pictures_fields' %>
      </div>
      <%= f.input :author, label: 'Auteur' %>
      <%= f.button :submit, 'Créer', class: "submit-btn" %>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="padded">
Here is the view of one post
<br>
<br>
<br>
<br>
  BOOOOOOOLLOOOOS

  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "real_logo_diametre.png" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
<!--         <li>
          <%#= link_to "BLOG", blog_path%>
        </li> -->
        <li>
          <%= link_to "A PROPOS", page_path('about') %>
        </li>
        <li>
          <%= link_to "CONTACT", page_path('contact') %>
        </li>
        <li>
          <%= link_to "http://www.facebook.com/diametrejeunecreation?fref=ts", target: "_blank" do %>
            <i class="fa fa-facebook-square"></i>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, id: "secret" do %>
            <i class="fa fa-circle-thin"></i>
          <% end %>
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Admin", admin_dashboard_path %>
        </li>
        <li>
          <%= link_to "Mon compte", account_path%>
        </li>
        <li>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
        </li>
        <%# else %>
          <li>
            <%#= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %>
          </li>
          <li>
            <%#= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
          </li>
        <% end %>
        <li>
          <%#= link_to t(".top_call_to_action", default: "Rent your flat"), "#", class: "btn" %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>